In [3]:
#1.Write a Python Program to Add Two Matrices

try:
    import numpy as np

    R = int(input("Enter the number of rows: "))
    C = int(input("Enter the number of columns: "))
    matrix = []
    for i in range(R):
        a = []
        for j in range(C):
            a.append(int(input()))
        matrix.append(a)    
    for i in range(R):
        for j in range(C):
            print(matrix[i][j] , end = " ")
        print()

    R1 = int(input("Enter the number of rows: "))
    C1 = int(input("Enter the number of columns: "))
    matrix2 = []
    for x in range(R1):
        b = []
        for y in range(C1):
            b.append(int(input()))
        matrix2.append(b)    
    for x in range(R1):
        for y in range(C1):
            print(matrix2[x][y] , end = " ")
        print()  
        
except Exception as e:
    print(e)
p = np.mat(matrix)
w = np.mat(matrix2)
print("The sum of matrix is \n", p+w)

Enter the number of rows: 2
Enter the number of columns: 2
1
2
3
4
1 2 
3 4 
Enter the number of rows: 2
Enter the number of columns: 2
5
6
7
8
5 6 
7 8 
The sum of matrix is 
 [[ 6  8]
 [10 12]]


In [6]:
#2.Write a Python Program to Multiply Two Matrices?

try:
    import numpy as np

    R = int(input("Enter the number of rows"))
    C = int(input("Enter the number of columns"))
    matrix = []
    for i in range(R):
        a = []
        for j in range(C):
            a.append(int(input()))
        matrix.append(a)    
    for i in range(R):
        for j in range(C):
            print(matrix[i][j] , end = " ")
        print()

    R1 = int(input("Enter the number of rows: "))
    C1 = int(input("Enter the number of columns: "))
    matrix2 = []
    for x in range(R1):
        b = []
        for y in range(C1):
            b.append(int(input()))
        matrix2.append(b)    
    for x in range(R1):
        for y in range(C1):
            print(matrix2[x][y] , end = " ")
        print() 
        
except Exception as e:
    print(e)
    
p = np.mat(matrix)
w = np.mat(matrix2)
print("The multiplication of matrix : \n" , p@w)

Enter the number of rows2
Enter the number of columns2
1
2
3
4
1 2 
3 4 
Enter the number of rows: 2
Enter the number of columns: 2
5
6
7
8
5 6 
7 8 
The multiplication of matrix : 
 [[19 22]
 [43 50]]


In [8]:
#3.Write a Python Program to Transpose a Matrix?

try:
    import numpy as np

    R = int(input("Enter the number of rows: "))
    C = int(input("Enter the number of columns: "))
    matrix = []
    for i in range(R):
        a = []
        for j in range(C):
            a.append(int(input()))
        matrix.append(a)    
    for i in range(R):
        for j in range(C):
            print(matrix[i][j] , end = " ")
        print()
        
except Exception as e:
    print(e)
p = np.mat(matrix)
print("Transpose of matrix is : \n" ,p.T, end=" ")

Enter the number of rows: 3
Enter the number of columns: 2
32
2
45
6
21
34
32 2 
45 6 
21 34 
Transpose of matrix is : 
 [[32 45 21]
 [ 2  6 34]] 

In [9]:
#4. Write a Python Program to Sort Words in Alphabetic Order?

try:
    
    def Func(S):
        W = S.split(" ")
        for i in range(len(W)):
        
            W[i]=W[i].lower()
            S = sorted(W)
        print(' '.join(S))
        
except Exception as e:
    print(e)




Func('FDFS ineuron class')



class fdfs ineuron


In [10]:
#5.Write a Python Program to Remove Punctuation From a String

try:
    
    import re

    test_str = str(input("Enter original input "))
    
    res = re.sub(r'[^\w\s]', '', test_str)
    print("The string after punctuation filter : " + res)

except Exception as e:
    print(e)

Enter original input tsyt$%#@yfvsyu%&
The string after punctuation filter : tsytyfvsyu
